[greeter]
background=/usr/share/backgrounds/login-bg.png
theme-name=Chroma-Greeter
icon-theme-name=Papirus-Dark
font-name=Fira Code 11
cursor-theme-name=Adwaita
cursor-theme-size=24
xft-antialias=true
xft-hintstyle=hintslight
user-background=false
hide-user-image=false
round-user-image=true
default-user-image=/usr/share/backgrounds/user-avatar.png
clock-format=%H:%M   %A, %d. %B
indicators=~host;~spacer;~clock;~spacer;~session;~power
position=50%,center 50%,center
panel-position=top
